export const PROTOCOL_VERSION = 3;

export const GATEWAY_OPERATOR_SCOPES = [
  'operator.read',
  'operator.admin',
  'operator.approvals',
  'operator.pairing',
] as const;

export const DEFAULT_GATEWAY_CLIENT_ID = 'gateway-client';
export const DEFAULT_GATEWAY_CLIENT_MODE = 'backend';
export const CONTROL_UI_CLIENT_ID = 'openclaw-control-ui';
export const CONTROL_UI_CLIENT_MODE = 'ui';

export type GatewayConnectMode = 'device' | 'control_ui';

export const GATEWAY_METHODS = [
  'health',
  'logs.tail',
  'channels.status',
  'channels.logout',
  'status',
  'usage.status',
  'usage.cost',
  'tts.status',
  'tts.providers',
  'tts.enable',
  'tts.disable',
  'tts.convert',
  'tts.setProvider',
  'config.get',
  'config.set',
  'config.apply',
  'config.patch',
  'config.schema',
  'exec.approvals.get',
  'exec.approvals.set',
  'exec.approvals.node.get',
  'exec.approvals.node.set',
  'exec.approval.request',
  'exec.approval.resolve',
  'wizard.start',
  'wizard.next',
  'wizard.cancel',
  'wizard.status',
  'talk.mode',
  'models.list',
  'agents.list',
  'agents.create',
  'agents.update',
  'agents.delete',
  'agents.files.list',
  'agents.files.get',
  'agents.files.set',
  'skills.status',
  'skills.bins',
  'skills.install',
  'skills.update',
  'update.run',
  'voicewake.get',
  'voicewake.set',
  'sessions.list',
  'sessions.preview',
  'sessions.patch',
  'sessions.reset',
  'sessions.delete',
  'sessions.compact',
  'last-heartbeat',
  'set-heartbeats',
  'wake',
  'node.pair.request',
  'node.pair.list',
  'node.pair.approve',
  'node.pair.reject',
  'node.pair.verify',
  'device.pair.list',
  'device.pair.approve',
  'device.pair.reject',
  'device.token.rotate',
  'device.token.revoke',
  'node.rename',
  'node.list',
  'node.describe',
  'node.invoke',
  'node.invoke.result',
  'node.event',
  'cron.list',
  'cron.status',
  'cron.add',
  'cron.update',
  'cron.remove',
  'cron.run',
  'cron.runs',
  'system-presence',
  'system-event',
  'send',
  'agent',
  'agent.identity.get',
  'agent.wait',
  'browser.request',
  'chat.history',
  'chat.abort',
  'chat.send',
] as const;

export const GATEWAY_EVENTS = [
  'connect.challenge',
  'agent',
  'chat',
  'presence',
  'tick',
  'talk.mode',
  'shutdown',
  'health',
  'heartbeat',
  'cron',
  'node.pair.requested',
  'node.pair.resolved',
  'node.invoke.request',
  'device.pair.requested',
  'device.pair.resolved',
  'voicewake.changed',
  'exec.approval.requested',
  'exec.approval.resolved',
] as const;

export const GATEWAY_METHODS_SET = new Set(GATEWAY_METHODS);
export const GATEWAY_EVENTS_SET = new Set(GATEWAY_EVENTS);

export function isKnownGatewayMethod(method: string): boolean {
  return GATEWAY_METHODS_SET.has(method as any);
}
